### ISSUE TITLE
loopback modules compatibilities

### ISSUE THREAD

**Issue by alexyma** [strongloop/loopback-connector-mssql#8]
loopback2.1.2 and loopback-connector-mssql require different versions of loopback-datasource-juggler as peer dependencies.

npm ERR! peerinvalid The package loopback-datasource-juggler does not satisfy it
s siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer loopback@2.1.2 wants loopback-datasource-juggler@^2.0.
0
npm ERR! peerinvalid Peer loopback-connector-mssql@1.0.1 wants loopback-datasour
ce-juggler@1.x

**Comment by dhmlau** [comment]
@alexyma, Sorry to take so long to respond.  Since this issue has been opened for more than 2.5 years, I'd like to close it as `loopback` and `loopback-connector-mssql` had released quite a number of versions since then. 
Feel free to reopen or open a new issue if you still encounter the problem.  Thanks.
